-- ============================================================================
-- Academic DBMS Project: INVENTORY MANAGEMENT
-- Script 07: Aggregate Functions, GROUP BY, and HAVING Queries
-- Demonstrating: COUNT, SUM, AVG, MIN, MAX, GROUP BY, and HAVING filtering
-- ============================================================================

USE inventory_management;

-- ----------------------------------------------------------------------------
-- 1. Table-Level Aggregate Summaries
-- ----------------------------------------------------------------------------

-- 1.1 Global Inventory Overview (Counts & Averages)
SELECT COUNT(*) AS Total_Products,
       SUM(Stock_Quantity) AS Total_Units_In_Stock,
       AVG(Price) AS Average_Product_Price,
       MIN(Price) AS Cheapest_Product_Price,
       MAX(Price) AS Most_Expensive_Product_Price,
       SUM(Stock_Quantity * Price) AS Total_Stock_Valuation
FROM Product;

-- 1.2 Global Procurement Financials (Purchases)
SELECT COUNT(Purchase_ID) AS Total_Purchase_Orders,
       SUM(Total_Amount) AS Total_Procurement_Expense,
       AVG(Total_Amount) AS Average_Purchase_Order_Value,
       MIN(Total_Amount) AS Smallest_Purchase_Order,
       MAX(Total_Amount) AS Largest_Purchase_Order
FROM Purchase;

-- 1.3 Global Revenue Financials (Sales)
SELECT COUNT(Sale_ID) AS Total_Sales_Invoices,
       SUM(Total_Amount) AS Total_Revenue_Generated,
       AVG(Total_Amount) AS Average_Sale_Value,
       MIN(Total_Amount) AS Smallest_Sale_Value,
       MAX(Total_Amount) AS Largest_Sale_Value
FROM Sale;


-- ----------------------------------------------------------------------------
-- 2. Aggregations with GROUP BY
-- ----------------------------------------------------------------------------

-- 2.1 Number of products and average price per category
SELECT c.Category_ID,
       c.Category_Name,
       COUNT(p.Product_ID) AS Number_Of_Products,
       AVG(p.Price) AS Average_Price,
       SUM(p.Stock_Quantity) AS Total_Category_Stock
FROM Category c
LEFT JOIN Product p ON c.Category_ID = p.Category_ID
GROUP BY c.Category_ID, c.Category_Name
ORDER BY Number_Of_Products DESC;

-- 2.2 Total procurement volume and money spent per supplier
SELECT s.Supplier_ID,
       s.Supplier_Name,
       COUNT(pu.Purchase_ID) AS Total_Orders_Placed,
       SUM(pu.Total_Amount) AS Total_Money_Paid
FROM Supplier s
INNER JOIN Purchase pu ON s.Supplier_ID = pu.Supplier_ID
GROUP BY s.Supplier_ID, s.Supplier_Name
ORDER BY Total_Money_Paid DESC;

-- 2.3 Total sales revenue generated by each customer
SELECT cu.Customer_ID,
       cu.Customer_Name,
       COUNT(sa.Sale_ID) AS Number_Of_Purchases,
       SUM(sa.Total_Amount) AS Total_Spent
FROM Customer cu
INNER JOIN Sale sa ON cu.Customer_ID = sa.Customer_ID
GROUP BY cu.Customer_ID, cu.Customer_Name
ORDER BY Total_Spent DESC;

-- 2.4 Total quantity sold and revenue generated per product
SELECT p.Product_ID,
       p.Product_Name,
       SUM(sd.Quantity) AS Total_Units_Sold,
       SUM(sd.Quantity * sd.Unit_Price) AS Total_Product_Revenue
FROM Product p
INNER JOIN Sale_Details sd ON p.Product_ID = sd.Product_ID
GROUP BY p.Product_ID, p.Product_Name
ORDER BY Total_Product_Revenue DESC;


-- ----------------------------------------------------------------------------
-- 3. Group Filtering with HAVING Clause
-- ----------------------------------------------------------------------------

-- 3.1 Categories containing strictly more than 2 products
SELECT c.Category_Name,
       COUNT(p.Product_ID) AS Product_Count
FROM Category c
INNER JOIN Product p ON c.Category_ID = p.Category_ID
GROUP BY c.Category_ID, c.Category_Name
HAVING COUNT(p.Product_ID) > 2;

-- 3.2 High-volume customers who have spent more than Rs. 5,000 in total
SELECT cu.Customer_Name,
       SUM(sa.Total_Amount) AS Total_Spent
FROM Customer cu
INNER JOIN Sale sa ON cu.Customer_ID = sa.Customer_ID
GROUP BY cu.Customer_ID, cu.Customer_Name
HAVING SUM(sa.Total_Amount) > 5000.00
ORDER BY Total_Spent DESC;

-- 3.3 Suppliers from whom we have ordered goods worth more than Rs. 25,000
SELECT s.Supplier_Name,
       SUM(pu.Total_Amount) AS Total_Procured_Value
FROM Supplier s
INNER JOIN Purchase pu ON s.Supplier_ID = pu.Supplier_ID
GROUP BY s.Supplier_ID, s.Supplier_Name
HAVING SUM(pu.Total_Amount) > 25000.00
ORDER BY Total_Procured_Value DESC;
